# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4819c3e11afbc4261d8a682307c16c9879a211fea2a62db49c346b6066e73ce1f208571e9639861b0aa9faafea4662e0802995de6ced670ca05141aee1e6590

test:
  secret_key_base: eb42383263fcdb41e46f3f7cdd02c7671111feabaaf929a35e8cced4c33f3883dfbcb4e06e2ebd639f429c7ca77f29c2b6871d4b22c7427027c1dd3068b044e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
